### ISSUE TITLE
Error for preparing fine-tuning training data

### ISSUE THREAD

**Issue by jiaboli007** [google-research/tapas#5]
Here is the error message when I run the first step of the sample code in TAPAS

/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/dask/dataframe/utils.py:14: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm
Traceback (most recent call last):
  File "tapas/tapas/run_task_main.py", line 32, in <module>
    from tapas.scripts import calc_metrics_utils
  File "/home/ec2-user/SageMaker/tapas/tapas/scripts/calc_metrics_utils.py", line 35, in <module>
    @dataclasses.dataclass
  File "/home/ec2-user/SageMaker/tapas/tapas/scripts/calc_metrics_utils.py", line 47, in Example
    pred_agg_function: int = _AggregationFunction.NONE
AttributeError: 'EnumTypeWrapper' object has no attribute 'NONE'

**Comment by muelletm** [comment]
Thanks for the report! Can you also sent us the command you are running?

**Comment by muelletm** [comment]
My best guess at this point is that the python proto-buffer code wasn't built correctly.

Basically the missing symbol is defined in the proto buffer:

```
message Answer {
  // Coordinates of cells that contain the answers.
  repeated AnswerCoordinate answer_coordinates = 1;

  // A function that is applied to the answer cells in order to obtain
  // the final answer.
  enum AggregationFunction {
    NONE = 0;
    // Sums all cell values. Numeric cells only.
    SUM = 1;
    // Averages all cell values. Numeric cells only.
    AVERAGE = 2;
    // Counts the number of answers.
    COUNT = 3;
  }
  optional AggregationFunction aggregation_function = 2;
  [...]
}
```

So if it's not defined then maybe the python code wasn't generated correctly.

Can you also share how you installed Tapas (the setup.py script will call the protoc compiler)?
And maybe check if there is an error message that could indicate what's going wrong?

**Comment by muelletm** [comment]
Okay, looking at [this](https://github.com/protocolbuffers/protobuf/issues/6028) it seems that not all protoc versions support accessing the enum value from the message. So basically you have to call `Answer.NONE` instead of `Answer.AggregationFunction.NONE`.

Can you share the protoc version you are using?

```bash
$ protoc --version
libprotoc 3.6.1
```

I also pushed a small change. Can you try if that fixes the issue?

**Comment by jiaboli007** [comment]
Thanks. I will try you new version. My protoc is 
libprotoc 3.11.4

I have another issue during fine-tuning training. I will test with your latest version and report the issue is the training problem is still there.

**Comment by jiaboli007** [comment]
This problem seems fixed with the latest version of TAPAS.

**Comment by muelletm** [comment]
Great!
